### ISSUE TITLE
Bug when reflecting tables 

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oedialect#35]
I tried to use saio to import the table model from db to sqlalchemy. That used to work out for me but since the new release, there might be a bug? I'm assuming this is caused by oedialect since I tried to run this using an older version (v0.0.6) and it worked. 

My code:

```
    # some db connection using the oedialect
    db = setup_db_connection()

    saio.register_schema("model_draft", db.engine)
    from saio.model_draft import Base
    # Import a random table. The line below triggers the error:
    from saio.model_draft import tum_urbs_ger_transmission
```

```
Traceback (most recent call last):
  File "f:/RLI/test-scripts/oep-uml/eralchemy-test.py", line 64, in <module>
    from saio.model_draft import tum_urbs_ger_transmission
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\saio.py", line 62, in memoizer
    cache[args] = func(*args)
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\saio.py", line 96, in __getattr__
    tab = sa.Table(name, self.Meta, autoload=True, schema=self.schema)
  File "<string>", line 2, in __new__
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\util\deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\sql\schema.py", line 560, in __new__
    metadata._remove_table(name, schema)
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\sql\schema.py", line 555, in __new__
    table._init(name, metadata, *args, **kw)
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\sql\schema.py", line 644, in _init
    self._autoload(
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\sql\schema.py", line 684, in _autoload
    bind.run_callable(
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\engine\base.py", line 2214, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\engine\base.py", line 1653, in run_callable
    return callable_(self, *args, **kwargs)
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\engine\default.py", line 469, in reflecttable
    return insp.reflecttable(
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\engine\reflection.py", line 665, in reflecttable
    for col_d in self.get_columns(
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\sqlalchemy\engine\reflection.py", line 391, in get_columns
    col_defs = self.dialect.get_columns(
  File "C:\Anaconda3\envs\oep-uml\lib\site-packages\oedialect\dialect.py", line 389, in get_columns
    column_info = self._get_column_info(
TypeError: _get_column_info() missing 1 required positional argument: 'generated'
```

**Comment by Ludee** [comment]
I can reproduce this bug and I am unable to retrieve data from the OEP

**Comment by MGlauer** [comment]
Which version of SQLAlchemy are you using?

**Comment by MGlauer** [comment]
It seems this field was introduced by a [newer version of SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy/commit/62b7dace0c1d03acf3224085d03a03684a969031) and the `OEDialect.get_column` does not reflect the changed interface yet. 

Shortterm fix: Use an older version of SQLAlchemy (My guess would be <= 3.15)
Longterm fix: We have to adapt this method and raise the minimal version of SQLAlchemy in the requirements.

**Comment by KirannBhavaraju** [comment]
### Reproducable

![image](https://user-images.githubusercontent.com/28805843/92129298-9d530e00-ee03-11ea-9d42-6628dbf9bdcc.png)

Using SQLAlchemy version i am using is 

![image](https://user-images.githubusercontent.com/28805843/92129469-da1f0500-ee03-11ea-8d20-d88b7f9d3024.png)

### Suggested Work around
Works with SQLAlchemy Version 1.3.14

![image](https://user-images.githubusercontent.com/28805843/92130834-7990c780-ee05-11ea-822c-23aa95a59553.png)

### Additions to the existing Workaround
This error pops up after the built of SQLAlchemy. So probably need to correct the version of `geoalchemy2`

```
oedialect 0.0.9 has requirement geoalchemy2<0.7.0, but you'll have geoalchemy2 0.8.4 which is incompatible.
```

**Comment by MGlauer** [comment]
As mentioned above: The issue is that the interface for reflecting tables changed in newer versions of SQLAlchemy. We should update the interface used by the dialect.

**Comment by KirannBhavaraju** [comment]
@MGlauer Is it okay if we don't use the new parameter while inferring schema? Will adding a `None` suffice. I am not really sure if we are planning to use this argument.
I am pasting the fuinction template and the usage below, from the sqlalchemy base for your reference.
 
`    def _get_column_info( self,
        name,
        format_type,
        default,
        notnull,
        domains,
        enums,
        schema,
        comment,
        generated ):`

Usage 

```
        # If a zero byte (''), then not a generated column.
        # Otherwise, s = stored. (Other values might be added in the future.)
        if generated:
            computed = dict(sqltext=default, persisted=generated == "s")
            default = None
        else:
            computed = None
```
Also the minimal sqlalchemy version would be changed to 1.3.16.

**Comment by jh-RLI** [comment]
Is there anything new here? Unfortunately, some tools are stuck with this bug because saio is used frequently. As @henhuy already stated in #36, the workaround with an older sqlalchemy version does not work. I have not tested the PR @KirannBhavaraju because the CI tests fail.

**Comment by KirannBhavaraju** [comment]
The PR basically has the requirement versions updated to mitigate this error.  Unfortunately i do not know why the CI fails. but the last time i discussed it with @MGlauer travis CI was causing the CI to break somehow.

**Comment by MGlauer** [comment]
The CI seems to be broken in general. I tried to fix it in `feature/travis`, but there were still some issues.

**Comment by Ludee** [comment]
This seems to be a critical bug in the OEP infrastructure.
We receive more and more request that the **oedialect** is not usable any more.

Seems like you developed a plan for a fix @MGlauer 
Can we assist you in any way? Do you have somebody at OvGU that can help?

**Comment by MGlauer** [comment]
This seems to be fixed with #37. Please close if it is.

**Comment by jh-RLI** [comment]
I will test this soon, thanks for the fix :+1:

**Comment by jh-RLI** [comment]
Tested it with the code provided at the top. No errors anymore. Can someone publish the new version on pypi?
