### ISSUE TITLE
Oedialect does not work with SQLAlchemy 1.4.0 or higher ?

### ISSUE THREAD

**Issue by mltja** [OpenEnergyPlatform/oedialect#42]
When testing eDisGo with an version of SQLAlchemy 1.4.0 or higher errors occur which are probably inflicted through oedialect.

## Error message
    
    self = <oedialect.compiler.OECompiler object at 0x7fdfa9d748d0>
    select = <sqlalchemy.sql.selectable.Select object at 0x7fdfa9d74c88>
    asfrom = False, parens = True, fromhints = None, compound_index = 0
    nested_join_translation = False, select_wraps_for = None, kwargs = {}
    jsn = {'command': 'advanced/search', 'type': 'select'}
    
        def visit_select(
            self,
            select,
            asfrom=False,
            parens=True,
            fromhints=None,
            compound_index=0,
            nested_join_translation=False,
            select_wraps_for=None,
            **kwargs
        ):
            jsn = {"command": "advanced/search", "type": "select"}
            needs_nested_translation = (
    >           select.use_labels
                and not nested_join_translation
                and not self.stack
                and not self.dialect.supports_right_nested_joins
            )
    E       AttributeError: 'Select' object has no attribute 'use_labels'
    
     #../../../lib/python3.6/site-packages/oedialect/compiler.py:614: AttributeError

**Comment by jh-RLI** [comment]
We currently do not support SQLAlchemy 1.4. use sqlalchemy == 1.3.16 instead. We have to update the interface but ATM this was not on our priolist, as the oedialect is working with the necessary modules.
